#### sklearn.preprocessing.LabelEncoder
#### 매개변수로 적는게 없음\
#### 객체선언하고 핏한다음에 트랜스폼
* fit -> transform 꼭 해줘야함

In [1]:
from sklearn.preprocessing import LabelEncoder # 라벨 인코더

In [4]:
items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서','하마']
#LabelEncoder를 객체로 생성한 후, fit()과 transform()으로  label인코딩 수행.
encoder=LabelEncoder()
print(encoder)
encoder.fit(items) #훈련시켜주는 것
labels=encoder.transform(items) # 
print('인코딩 변환값:',labels)



LabelEncoder()
인코딩 변환값: [0 1 4 5 3 3 2 2 6]


In [3]:
print('인코딩 클래스:',encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']


In [6]:
print('디코딩 원본 값:',encoder.inverse_transform([3,4,3,1,0,2,2,3,5]))
#인코딩한거 디콩딩으로 만들어주는 값

디코딩 원본 값: ['선풍기' '전자렌지' '선풍기' '냉장고' 'TV' '믹서' '믹서' '선풍기' '컴퓨터']


### sklearn.preprocessing.OneHotEncoder
### (*, categories='auto', drop=None, sparse=True, dtype=<class 'numpy.float64'>, handle_unknown='error')

In [9]:
items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']
#LabelEncoder를 객체로 생성한 후, fit()과 transform()으로  label인코딩 수행.
encoder=LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)
print('인코딩 변환값:',labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


In [11]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np


In [20]:
items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서','하마']
encoder=LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)
labels=labels.reshape(-1,1) #변환할 수 있게 
print(labels)#reshape은 값들을 아예 따로 나오게 끔 함
#


[[0]
 [1]
 [4]
 [5]
 [3]
 [3]
 [2]
 [2]
 [6]]


In [14]:
oh_encoder=OneHotEncoder() #배열로 나올 수 있게 끔 함
oh_encoder.fit(labels)
oh_labels=oh_encoder.transform(labels)
print('원핫 인코딩 데이터')
print(oh_labels.toarray())
print('원핫 인코딩 데이터')
print(oh_labels.shape)

원핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
원핫 인코딩 데이터
(9, 7)
