In [1]:
import numpy as np
data2=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]


In [2]:
arr=np.array(data2)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr[0][0]
arr[0,0]


1

In [4]:
arr[1][1]we

5

In [5]:
arr[(0,1,2),(0,1,2)] # 


array([1, 5, 9])

In [6]:
arr[[1,2,0]] #행인덱싱 

array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])